In [5]:
import pandas as pd
import numpy as np
import openpyxl as xl 
# connect to sas server
import os
os.environ["PATH"] += ';'+r'C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'

import saspy
sas = saspy.SASsession(cfgname = 'winiomlinux', omruser = 'CYLM' )
# then pw

Please enter the password for IOM user CYLM: ········
SAS Connection established. Subprocess id is 4968

In [6]:
c = sas.submit("""
libname EDMMRT oracle user='cylm' password="System#01" path='ADWPRD' schema = 'EDMMRT';

/* Comment 1  /* Comment 2 */  

proc sql; 
create table CompeteConn as 
select 
* 
from 
edmmrt.Call_Activity_Dim
where call_dt = '01oct2018'd and comp_conn_flg = 'X'; 
quit; 

""")
# print(c['LOG'])

In [7]:
# Take the work folder created above
# pull down

CallData = sas.sasdata2dataframe('CompeteConn', 'work')

In [8]:
# print data in sas now in jupyter
CallData

,CALL_KEY,CALL_DT,INTERACTION_ID,STARTTM,ENDTM,RPT_WK,RPT_MTH,TENANT_NAME,INTERACTION_RESOURCE_ID,INTERACTION_TYPE,...,MASS_FLG,SEM_FLG,CREATED_DT,CREATED_LOAD_ID,MODIFIED_DT,MODIFIED_LOAD_ID,MODIFIED_RECORD_NUM,RECORD_STATUS,LOAD_DT,BATCH_DT
0,32992728,2018-10-01,571903746,2018-10-01 18:54:32,2018-10-01 19:17:27,2018-10-07,2018-10-01,Resources,3313321870,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
1,32989540,2018-10-01,571891396,2018-10-01 17:53:08,2018-10-01 18:33:01,2018-10-07,2018-10-01,Resources,3313266946,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
2,32992960,2018-10-01,571904478,2018-10-01 19:04:37,2018-10-01 19:25:33,2018-10-07,2018-10-01,Resources,3313329962,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
3,32993599,2018-10-01,571906870,2018-10-01 19:27:57,2018-10-01 19:38:45,2018-10-07,2018-10-01,Resources,3313342818,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
4,32990080,2018-10-01,571893516,2018-10-01 18:10:37,2018-10-01 18:34:03,2018-10-07,2018-10-01,Resources,3313276074,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
5,32996483,2018-10-01,571918320,2018-10-01 20:38:36,2018-10-01 20:45:22,2018-10-07,2018-10-01,Resources,3313401178,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
6,32964529,2018-10-01,571789642,2018-10-01 14:21:58,2018-10-01 14:36:48,2018-10-07,2018-10-01,Resources,3312742034,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
7,32970268,2018-10-01,571814240,2018-10-01 15:05:12,2018-10-01 15:26:03,2018-10-07,2018-10-01,Resources,3312860898,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
8,32969106,2018-10-01,571809368,2018-10-01 15:11:27,2018-10-01 15:15:57,2018-10-07,2018-10-01,Resources,3312839770,Outbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
9,32968952,2018-10-01,571808768,2018-10-01 14:59:02,2018-10-01 15:16:38,2018-10-07,2018-10-01,Resources,3312835614,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
10,32967337,2018-10-01,571801726,2018-10-01 15:01:28,2018-10-01 15:02:41,2018-10-07,2018-10-01,Resources,3312803578,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
11,32966718,2018-10-01,571799038,2018-10-01 14:40:25,2018-10-01 14:57:43,2018-10-07,2018-10-01,Resources,3312793078,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
12,32967043,2018-10-01,571800854,2018-10-01 14:39:49,2018-10-01 14:59:20,2018-10-07,2018-10-01,Resources,3312795086,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
13,32921193,2018-10-01,571602438,2018-10-01 08:34:31,2018-10-01 08:34:31,2018-10-07,2018-10-01,Resources,3311775722,Internal,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
14,32919175,2018-10-01,571594250,2018-10-01 07:36:22,2018-10-01 08:08:10,2018-10-07,2018-10-01,Resources,3311734134,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
15,32918853,2018-10-01,571592924,2018-10-01 07:49:39,2018-10-01 08:01:43,2018-10-07,2018-10-01,Resources,3311726194,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
16,32919184,2018-10-01,571594268,2018-10-01 07:47:47,2018-10-01 08:09:03,2018-10-07,2018-10-01,Resources,3311734262,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
17,32920639,2018-10-01,571600274,2018-10-01 08:06:44,2018-10-01 08:27:06,2018-10-07,2018-10-01,Resources,3311766086,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
18,32917768,2018-10-01,571588380,2018-10-01 07:27:04,2018-10-01 07:46:44,2018-10-07,2018-10-01,Resources,3311701830,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
19,32948940,2018-10-01,571718878,2018-10-01 11:57:46,2018-10-01 12:34:01,2018-10-07,2018-10-01,Resources,3312372950,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
20,32949236,2018-10-01,571719846,2018-10-01 12:09:06,2018-10-01 12:36:51,2018-10-07,2018-10-01,Resources,3312396966,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
21,32949700,2018-10-01,571722128,2018-10-01 12:20:16,2018-10-01 12:35:35,2018-10-07,2018-10-01,Resources,3312396858,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
22,32950339,2018-10-01,571725058,2018-10-01 12:11:49,2018-10-01 12:41:44,2018-10-07,2018-10-01,Resources,3312416558,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
23,32950344,2018-10-01,571725066,2018-10-01 12:11:44,2018-10-01 12:40:23,2018-10-07,2018-10-01,Resources,3312416006,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
24,32948539,2018-10-01,571716790,2018-10-01 12:17:21,2018-10-01 12:30:47,2018-10-07,2018-10-01,Resources,3312384478,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
25,32981225,2018-10-01,571858134,2018-10-01 16:37:50,2018-10-01 16:55:05,2018-10-07,2018-10-01,Resources,3313088186,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
26,32984970,2018-10-01,571873134,2018-10-01 17:12:23,2018-10-01 17:34:13,2018-10-07,2018-10-01,Resources,3313175302,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
27,32987491,2018-10-01,571883268,2018-10-01 17:57:41,2018-10-01 17:58:12,2018-10-07,2018-10-01,Resources,3313220218,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
28,32981239,2018-10-01,571858202,2018-10-01 16:44:52,2018-10-01 16:58:55,2018-10-07,2018-10-01,Resources,3313090214,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
29,32987200,2018-10-01,571881914,2018-10-01 17:43:00,2018-10-01 18:01:43,2018-10-07,2018-10-01,Resources,3313221522,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,32975552,2018-10-01,571835804,2018-10-01 15:49:36,2018-10-01 16:11:28,2018-10-07,2018-10-01,Resources,3312979174,Outbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
87,32971139,2018-10-01,571817512,2018-10-01 15:10:43,2018-10-01 15:34:47,2018-10-07,2018-10-01,Resources,3312884370,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
88,32972472,2018-10-01,571822970,2018-10-01 15:21:09,2018-10-01 15:46:00,2018-10-07,2018-10-01,Resources,3312900102,Outbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
89,32975109,2018-10-01,571833672,2018-10-01 15:54:13,2018-10-01 16:08:32,2018-10-07,2018-10-01,Resources,3312978106,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
90,32976431,2018-10-01,571839150,2018-10-01 16:17:47,2018-10-01 16:18:58,2018-10-07,2018-10-01,Resources,3312999238,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
91,32977095,2018-10-01,571841860,2018-10-01 16:06:08,2018-10-01 16:24:50,2018-10-07,2018-10-01,Resources,3313008942,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
92,32976442,2018-10-01,571839360,2018-10-01 15:55:36,2018-10-01 16:25:04,2018-10-07,2018-10-01,Resources,3313002366,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
93,32977925,2018-10-01,571845224,2018-10-01 15:45:29,2018-10-01 16:31:10,2018-10-07,2018-10-01,Resources,3313024746,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
94,32971873,2018-10-01,571820478,2018-10-01 15:11:40,2018-10-01 15:44:25,2018-10-07,2018-10-01,Resources,3312906258,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
95,32973510,2018-10-01,571827524,2018-10-01 15:37:14,2018-10-01 15:55:58,2018-10-07,2018-10-01,Resources,3312935018,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
96,32973514,2018-10-01,571827538,2018-10-01 15:38:32,2018-10-01 15:54:38,2018-10-07,2018-10-01,Resources,3312933742,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
97,32978426,2018-10-01,571847064,2018-10-01 16:25:08,2018-10-01 16:37:33,2018-10-07,2018-10-01,Resources,3313045046,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
98,32975665,2018-10-01,571835996,2018-10-01 15:53:14,2018-10-01 16:15:39,2018-10-07,2018-10-01,Resources,3312984646,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
99,32971222,2018-10-01,571817826,2018-10-01 15:16:51,2018-10-01 15:40:32,2018-10-07,2018-10-01,Resources,3312889118,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
100,32954262,2018-10-01,571742602,2018-10-01 12:57:28,2018-10-01 13:14:04,2018-10-07,2018-10-01,Resources,3312502434,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
101,32954725,2018-10-01,571744326,2018-10-01 13:07:42,2018-10-01 13:19:38,2018-10-07,2018-10-01,Resources,3312519102,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
102,32953406,2018-10-01,571738254,2018-10-01 12:49:34,2018-10-01 13:10:17,2018-10-07,2018-10-01,Resources,3312494474,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
103,32954600,2018-10-01,571743998,2018-10-01 12:24:08,2018-10-01 12:50:33,2018-10-07,2018-10-01,Resources,3312435770,Outbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
104,32953412,2018-10-01,571738276,2018-10-01 12:51:00,2018-10-01 13:07:38,2018-10-07,2018-10-01,Resources,3312493250,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
105,32957442,2018-10-01,571756786,2018-10-01 13:20:08,2018-10-01 13:37:29,2018-10-07,2018-10-01,Resources,3312573598,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
106,32957584,2018-10-01,571757386,2018-10-01 13:25:31,2018-10-01 13:42:07,2018-10-07,2018-10-01,Resources,3312590050,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
107,32959196,2018-10-01,571765260,2018-10-01 13:49:52,2018-10-01 13:50:49,2018-10-07,2018-10-01,Resources,3312608834,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
108,32958491,2018-10-01,571762098,2018-10-01 13:25:05,2018-10-01 13:44:31,2018-10-07,2018-10-01,Resources,3312591710,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
109,32959697,2018-10-01,571767736,2018-10-01 13:35:22,2018-10-01 13:56:50,2018-10-07,2018-10-01,Resources,3312620254,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
110,32960498,2018-10-01,571771238,2018-10-01 13:40:58,2018-10-01 14:08:27,2018-10-07,2018-10-01,Resources,3312651414,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
111,32957504,2018-10-01,571757122,2018-10-01 13:17:32,2018-10-01 13:37:30,2018-10-07,2018-10-01,Resources,3312573622,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
112,32953360,2018-10-01,571738110,2018-10-01 11:50:27,2018-10-01 13:06:12,2018-10-07,2018-10-01,Resources,3312492262,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
113,32954084,2018-10-01,571741416,2018-10-01 12:56:09,2018-10-01 13:14:42,2018-10-07,2018-10-01,Resources,3312502670,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
114,32959901,2018-10-01,571768464,2018-10-01 13:34:07,2018-10-01 14:00:40,2018-10-07,2018-10-01,Resources,3312641778,Inbound,...,NaN,NaN,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08
115,32959908,2018-10-01,571768480,2018-10-01 13:41:42,2018-10-01 13:59:06,2018-10-07,2018-10-01,Resources,3312638946,Inbound,...,NaN,X,2018-10-08,19424,NaT,NaN,NaN,A,2018-10-08,2018-10-08

In [12]:
# Different ways to pull back data 


# Assign directly the path and lib 
sas.saslib('S1612', path = '/SAS/data/res_analytics/Bus_Intel/Month_End_Data/Monthend/dhsap/201612')

# Then pull back data 
ending_File = sas.sasdata('DM_2016_12_ENDING', 'S1612')

ending_File.head()

5                                                          The SAS System                             15:46 Monday, October 29, 2018

31
32         libname S1612    '/SAS/data/res_analytics/Bus_Intel/Month_End_Data/Monthend/dhsap/201612'  ;
NOTE: Libref S1612 was successfully assigned as follows:
      Engine:        V9
      Physical Name: /SAS/data/res_analytics/Bus_Intel/Month_End_Data/Monthend/dhsap/201612
33
34

,product_gp2,dwelling_type,product_gp,product_subgp,risk_segment,usage,transaction,term_length,uccontract,region,...,price_p1,acct_open_date,begin_dt,end_dt,term_end_month,tenure_month,tenure,term_month_left,TML_flag,tml_flag_old
0,MTM_PTC,SINGLE,MTM_PTC,MTM_PTC,6High Risk,2. 6-12k,NaN,NaN,9000126764,NTX,...,15 < P <=16,1995-10-19,1995-10-19,2016-12-31,NaT,254,4. > 24 mos.,NaN,NaN,NaN
1,MTM_PTC,MULTI,MTM_PTC,MTM_PTC,1Excellent,2. 6-12k,NaN,NaN,9000126765,NTX,...,15 < P <=16,1995-10-17,1995-10-17,2016-12-31,NaT,254,4. > 24 mos.,NaN,NaN,NaN
2,MTM_PTC,SINGLE,MTM_PTC,MTM_PTC,1Excellent,3. 12-18k,NaN,NaN,9000126767,NTX,...,15 < P <=16,1995-10-24,1995-10-24,2016-12-31,NaT,254,4. > 24 mos.,NaN,NaN,NaN
3,MTM_PTC,SINGLE,MTM_PTC,MTM_PTC,2Good,2. 6-12k,NaN,NaN,9000126772,NTX,...,15 < P <=16,2008-06-06,2008-06-06,2016-12-31,NaT,102,4. > 24 mos.,NaN,NaN,NaN
4,Term,SINGLE,Term,24 Term,4Basic,2. 6-12k,NaN,24.0,9000126774,NTX,...,12 < P <=13,1998-01-23,1998-01-23,2016-12-31,2017-10-28,227,4. > 24 mos.,10.0,> 90 day,> 90 day


I found this to be helpful becasue python allows you to save onto sharepoint sites easier than SAS

In [35]:
# for example 
sas.saslib('f_calls', path="/SAS/data/res_analytics/Bus_Intel/EVS/A8OJ/cc_datasets/calls/for_friel")


DnisLookup = sas.sasdata2dataframe('DNIS_Lookup','F_calls')

11                                                         The SAS System                             16:17 Friday, October 26, 2018

209
210        libname f_calls    '/SAS/data/res_analytics/Bus_Intel/EVS/A8OJ/cc_datasets/calls/for_friel'  ;
NOTE: Libref F_CALLS was successfully assigned as follows:
      Engine:        V9
      Physical Name: /SAS/data/res_analytics/Bus_Intel/EVS/A8OJ/cc_datasets/calls/for_friel
211
212

In [10]:
writer = pd.ExcelWriter(r'X:\John Friel\outputTest1.xlsx')
# DnisLookup.to_excel(writer,'Dnis Lookup')
CallData.to_excel(writer,'Complete Connect Data')

workbook  = writer.book
antyhing = writer.sheets['Complete Connect Data']
writer.save()

In [ ]:
writer = pd.ExcelWriter(r"C:\Users\cylm\Documents\PowerOn\ACQ Power On Contest " + FileDate + " MGA.xlsx", engine='xlsxwriter' )
CallData.to_excel(writer,'Complete Connect Data')